name: Init package
on:
  workflow_dispatch:
jobs:
  build:
    name: init
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init
        run: |
          cd ${{ GITHUB.WORKSPACE }}
          swift package init
