name: Init package
on:
  workflow_dispatch:
jobs:
  build:
    permissions:
      contents: write
    name: init
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Init
        run: |
          cd ${{ GITHUB.WORKSPACE }}
          swift package init
      - name: Setup credentials
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
