name: iOS Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: Build and Create IPA
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Select Xcode
      run: sudo xcode-select -switch /Applications/Xcode.app
      
    - name: Build archive
      run: |
        xcodebuild clean archive \
          -workspace "Spawn-Me-2.0.xcworkspace" \
          -scheme "Spawn-Me-2.0" \
          -archivePath $PWD/build/Spawn-Me-2.0.xcarchive \
          -configuration Release \
          IPHONEOS_DEPLOYMENT_TARGET=15.8.2 \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO \
          CODE_SIGNING_ALLOWED=NO
          
    - name: Export IPA
      run: |
        xcodebuild -exportArchive \
          -archivePath $PWD/build/Spawn-Me-2.0.xcarchive \
          -exportOptionsPlist exportOptions.plist \
          -exportPath $PWD/build \
          -allowProvisioningUpdates
          
    - name: Upload IPA
      uses: actions/upload-artifact@v2
      with:
        name: Spawn-Me-2.0.ipa
        path: ${{ github.workspace }}/build/*.ipa
